plugins { id 'com.android.application' }

android {
    namespace 'com.drburghash.bmsblank'
    compileSdk 35

    defaultConfig {
        applicationId 'com.drburghash.homehubx'
        minSdk 26
        targetSdk 29
        versionCode 102
        versionName '4.2-widget-final'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
