plugins { id 'com.android.application' }

android {
    namespace 'com.drburghash.bmsblank'
    compileSdk 35

    defaultConfig {
        applicationId 'com.drburghash.homehubx'
        minSdk 26
        targetSdk 29
        versionCode 103
        versionName '4.3-widget-5rows'
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
